### ISSUE TITLE
another feature for approval

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#10]
@xuanxu would it be possible for a responder to add a field to the issue body?

More specifically I'd like the approve command to add a field "Date accepted" to the issue body, with the date of the day the command was run.

Cc @karthik (your idea)

**Comment by xuanxu** [comment]
Sure it's possible. Ideally the place where the new field should be added is previously marked with HTML comments, otherwise it can be added at the end or at the beggining of the issue body.

**Comment by maelle** [comment]
Can it be

* HTML comment if it exist
* Beginning of the issue body otherwise?

This way it'll be easier to make it work with currently open issues (or future malformatted issues, as long as we don't use form-based submissions that's a risk).

**Comment by xuanxu** [comment]
>     * HTML comment if it exist
> 
>     * Beginning of the issue body otherwise?
 
 Yes, this can be added
