### ISSUE TITLE
Ensure all label sequences are automated

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#104]
This is the more general issue behind #102 and #103. Our labels are:

![](https://img.shields.io/github/labels/ropensci/software-review/0\editorial-team-prep)
![](https://img.shields.io/github/labels/ropensci/software-review/0\presubmission)
![](https://img.shields.io/github/labels/ropensci/software-review/1\editor-checks)
![](https://img.shields.io/github/labels/ropensci/software-review/2\seeking-reviewer(s))
![](https://img.shields.io/github/labels/ropensci/software-review/3\reviewer(s)-assigned)
![](https://img.shields.io/github/labels/ropensci/software-review/4\review(s)-in-awaiting-changes)
![](https://img.shields.io/github/labels/ropensci/software-review/5\awaiting-reviewer(s)-response)
![](https://img.shields.io/github/labels/ropensci/software-review/6\approved)

And we have the following transitions in [our `config/settings-production.yml`](https://github.com/ropensci-org/buffy/blob/ropensci/config/settings-production.yml):

- [ ] ![](https://img.shields.io/github/labels/ropensci/software-review/0\editorial-team-prep) is not automatically added (#102)
- [x] ![](https://img.shields.io/github/labels/ropensci/software-review/0\editorial-team-prep) :arrow_right:  ![](https://img.shields.io/github/labels/ropensci/software-review/1\editor-checks) in [`assign_editor` responder](https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L103-L110)
- [x] ![](https://img.shields.io/github/labels/ropensci/software-review/1\editor-checks) :arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/2\seeking-reviewer(s)) in [`seeking_reviewers` responder](https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L60-L67)
- [x] ![](https://img.shields.io/github/labels/ropensci/software-review/2\seeking-reviewer(s)) :arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/3\reviewer(s)-assigned) in [`seeking_reviewers` responder](https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L89-L102)
- [x] ![](https://img.shields.io/github/labels/ropensci/software-review/3\reviewer(s)-assigned):arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/4\review(s)-in-awaiting-changes) - in [`submit_reviews` responder](https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L13-L21)
- [ ] ![](https://img.shields.io/github/labels/ropensci/software-review/4\review(s)-in-awaiting-changes):arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/5\awaiting-reviewer(s)-response) - not currently automated
- [x] ![](https://img.shields.io/github/labels/ropensci/software-review/5\awaiting-reviewer(s)-response):arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/6\approved) - in [`approve` responder](https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L68-L84)

So we're missing two stages in our automation:
- Initially adding ![](https://img.shields.io/github/labels/ropensci/software-review/0\editorial-team-prep)
- ![](https://img.shields.io/github/labels/ropensci/software-review/4\review(s)-in-awaiting-changes):arrow_right: ![](https://img.shields.io/github/labels/ropensci/software-review/5\awaiting-reviewer(s)-response)

Comments please @maelle @noamross. In particular, it seems the following questions need answering:

1. What command or automation step could/should we use to automatically add ![](https://img.shields.io/github/labels/ropensci/software-review/0\editorial-team-prep)? Should we detect that checks are okay, and auto-add label then?
2. What command should we add to transition `4\` :arrow_right: `5\`? Should it be able to be issued by both editor and author?

**Comment by maelle** [comment]
> What command should we add to transition 4\ ➡️ 5\? Should it be able to be issued by both editor and author?

Isn't it https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L18?

**Comment by mpadge** [comment]
Yes, i guess so :question: Trick there would be that those are *individual* responses, and there is no equivalent of this:
https://github.com/ropensci-org/buffy/blob/044d630b554a7963aa2a1d8febe9422edd5643bd/config/settings-production.yml#L16-L17
that is, no way of identifying an `all_responses_in` event...

**Comment by maelle** [comment]
this is a responder for the author to indicate where the response is. Only one such response is expected.

**Comment by mpadge** [comment]
Okay, then that would indeed be the place. Do you want to update #103 with that change?

**Comment by maelle** [comment]
That's what #103 does?

**Comment by mpadge** [comment]
Aha - :bulb: goes on in my :brain: :exclamation: ... then the only remaining problem is that it is not a proper transition. The good news for me is that it means this issue was still worthwhile. And what I think i now need to ask you to do is also:
``` yaml
add_labels:
  - 5/awaiting-reviewer(s)-responses
```
Right :question:

**Comment by maelle** [comment]
Right!

**Comment by mpadge** [comment]
@maelle Just cleaning out some issues, including closing this one which I think is okay now.
