### ISSUE TITLE
reviewers not able to use the check command

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#106]
https://github.com/ropensci/software-review/issues/633#issuecomment-2158854136

**Comment by mpadge** [comment]
Actual problem is that reviewers are listed without the prefixed "@", so not identified by GitHub handles, and therefore prohibited. Fix needs to ensure initial reviewer handles are pre-prended with "@".

**Comment by maelle** [comment]
or could the code add the @ if it's not there, so "just" making the code more robust?

**Comment by mpadge** [comment]
All okay; it was actually editors fault through issuing command `assign person as reviewer` rather than `assign @person as reviewer`.
