### ISSUE TITLE
Responder to check presence of all expected variables

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#14]
@xuanxu We'll end up with a number of variables which are all embedded in html comments in the issue templates. In spite of our best efforts at telling people not to delete these, it is likely to happen anyway, and so it would be useful to have an initial responder that is called as soon as an issue is opened and simply checks for the presence of all expected variables, and issues some kind of message if any have been removed. The `if` clauses respond to the presence of variables, but this would need to respond to their potential absence - hopefully you'll be able to tell @maelle and myself how that can be done?

**Comment by xuanxu** [comment]
This should be a specific responder listening to the 'issue opened' event. I think it's general enough to be added as a standard Buffy responder, so I've opened an issue there: https://github.com/openjournals/buffy/issues/43

**Comment by maelle** [comment]
Thank you!!

**Comment by maelle** [comment]
We have placeholders like the reviewers list where the initial value is easy to guess, and we also have variables we want authors not to delete like repourl (i.e. they need to keep the HTML comment). Can these be handled differently? In the second case we'd need a warning. Sorry if I'm missing something obvious!

**Comment by mpadge** [comment]
The external check called as part of the welcome responder also includes a variable check. I thought this meant that could be removed, but am thinking it's good to keep it, because it does a little more than just check presence/absence; for example ensuring that the `author` variable is just a single GitHub handle. No harm leaving it on as well, so this is just a cross-record that the checks are effectively run twice. This `buffy` version of course remains the definitive authority!

**Comment by maelle** [comment]
Ok, thanks! I'll wait for @xuanxu's answer before tweaking our config.

**Comment by xuanxu** [comment]
> We have placeholders like the reviewers list where the initial value is easy to guess, and we also have variables we want authors not to delete like repourl (i.e. they need to keep the HTML comment). Can these be handled differently? In the second case we'd need a warning. Sorry if I'm missing something obvious!

The params in the configuration of this responder are set per variable, so you can configure each placeholder differently. So for example, you can set a message warning only for repourl and not for reviewers:
```yaml
responders:
    initial_values:
      values:
        - reviewers
        - repourl:
          - heading: Repository 
          - warn_if_empty: true 
```
With this config if the author deletes the repourl, the responder will add the html-comment back and post a comment warning that it is empty.

**Comment by mpadge** [comment]
Shall we close this now then? Thanks as always @xuanxu :partying_face:

**Comment by maelle** [comment]
No, not before I add the configuration which I will do soon! Thanks both!
