### ISSUE TITLE
Responder to call external API service when issue first opened

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#19]
@xuanxu Next on our list of requirements is a responder that calls an external API endpoint when an issue is opened. That API returns immediately with an arbitrary value (or nothing at all), and is used just to trigger a separate service. The external service configuration is identical to current one in our config settings:

https://github.com/ropensci-org/buffy/blob/208f2f11467dd86c814d824f7d41cf4846b336ca/config/settings-production.yml#L79-L92

How can we (re-)configure the `welcome` responder to include this external service call?

**Comment by xuanxu** [comment]
This sounds like an `external_service` responder but triggered by the `issue.opened` event instead of `comment.created`.
I'm going to investigate if this can be moved to config or we need a new responder.

**Comment by xuanxu** [comment]
This can be done now with the updated `Welcome` responder. Closing the issue.
