### ISSUE TITLE
Airtable Slack invites missing author

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/buffy#32]
For slack-invites auto-added to Airtable, cffr pkg reviewers were added to [Airtable slack-invites tab](https://airtable.com/app8dssb6a7PG6Vwj/tblDyjd5Qag4ptDXO/viwC3koktThqduPEO?blocks=hide) but author was not. https://github.com/ropensci/software-review/issues/463

**Comment by maelle** [comment]
Thank you. Solved via changing the formatting of the submission templates (and of all open submissions).

cc @xuanxu @mpadge

**Comment by dieghernan** [comment]
I didn’t receive notification, should I?

**Comment by stefaniebutland** [comment]
Hi @dieghernan. I'm rOpenSci's Community Manager. I'll send you an invitation to our Slack shortly!

**Comment by stefaniebutland** [comment]
sent :-)
