### ISSUE TITLE
Custom responder to make the check package command runnable by all usernames mentioned in the reviewers and authors (author1, author-others, reviewers-list)

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#34]
@xuanxu could we tweak the configuration so that the check package command is runnable by all usernames mentioned in the reviewers and authors (author1, author-others, reviewers-list)? I.e. is that possible?

**Comment by xuanxu** [comment]
Changing permissions to a different list of users for each issue can't be done in the configuration. The way to do it would be to create a custom responder with the access rules specified there instead of using a regular responder.

**Comment by mpadge** [comment]
Very easy from external service side to control all that, by modifying current template check fn to also extract all "authorised" users, and send on to check service if sender is in list.

**Comment by maelle** [comment]
I'd be in favor of having the logic in the responder, would that be ok with you @mpadge?

**Comment by mpadge** [comment]
Definitely okay! I too think that that is best

**Comment by maelle** [comment]
Thanks @mpadge!

@xuanxu this is becoming a feature request for you then. :smile_cat: 

I edited the issue title.

**Comment by mpadge** [comment]
This is all done now via the above commits; thanks @xuanxu and @maelle.
