### ISSUE TITLE
How to make warning of initial value responder more informative?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#44]
@xuanxu 

Instead of just listing the missing variables, could the message mention the submission template? Something like "Make sure you haven't deleted HTML comments when filling the submission template".

Cc @mpadge

**Comment by xuanxu** [comment]
Sure, I can add anything to that message. But I thought it was a message to inform or directed to the editor, more than to the author. Because does the author know how to go back and re-add the deleted HTML comments/missing values?

**Comment by maelle** [comment]
Good point, I take my feature request back! Thank you!
