### ISSUE TITLE
Should the team created by the bot be secret?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#46]
It's currently the case. What was the reason for this choice @xuanxu, was it the default?

**Comment by xuanxu** [comment]
I had to look into it. It seems that `secret` (only visible to organization owners and members of this team) is the default: https://docs.github.com/en/rest/reference/teams#create-a-team

Should we change it to `closed`?

**Comment by maelle** [comment]
Yes please! :pray: 

What a weird contrary of "secret"!

**Comment by xuanxu** [comment]
[Done!](https://github.com/ropensci-org/buffy/commit/a558c97e1bbf556aa29ca27e3cf0f9b4cd6d17be)

**Comment by maelle** [comment]
Thank you!
