### ISSUE TITLE
Convert date columns in Airtable to ISO format

### ISSUE THREAD

**Issue by annakrystalli** [ropensci-org/buffy#48]
Convert all columns involving dates to `YYYY-MM-DD`

**Comment by maelle** [comment]
@xuanxu if we change the data format, will this change the API call in the responder that logs reviews?

**Comment by xuanxu** [comment]
Yes, the calls should be updated (trivial change, we can have it ready in the ropensci branch to deploy once the columns are change in Airtable).
The API calls involving dates are the ones creating entries in the `reviews` and `slack-invites` tables

**Comment by xuanxu** [comment]
Pull request ready here: #49

**Comment by maelle** [comment]
Thanks a ton @xuanxu!!

**Comment by maelle** [comment]
(change made in Airtable before merging the PR)
