### ISSUE TITLE
Different transfer process

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#52]
Right now the bot invite the package author to the GitHub organization and they transfer the repo then use the finalize transfer command (that gives them admin rights back).

@xuanxu does it sound feasible to have
- the package author is invited to the GitHub organization and has to accept the invitation;
- the package author adds ropensci-review-bot as admin to their repo;
- the package author uses the finalize command;
- ropensci-review-bot accepts the invitation to the repo, transfer the repo to the GitHub organization, and then gives admin rights back to the package author;
- ropensci-review-bot adds the package name and git repo URL to a JSON somewhere (somewhere = a repo in the GitHub organization) to "register" it.

**Comment by maelle** [comment]
Cc @jeroen

**Comment by maelle** [comment]
I've now realized that if the repo is in a personal account (as opposed to an organization), the author will have to _transfer_ the repo to ropensci-review-bot. Indeed you cannot add another admin to a personal repository. Therefore maybe it is better if in all cases, org or personal repo, the author transfers their repo to ropensci-review-bot. So the updated process would be

- the package author is invited to the GitHub organization and has to accept the invitation;
- the package author starts the transfer of their repo to ropensci-review-bot;
- the package author uses the finalize command;
- ropensci-review-bot accepts the transfer of the repo to its "personal" account, transfer the repo to the GitHub organization, and then gives admin rights back to the package author;
- ropensci-review-bot adds the package name and git repo URL to a JSON somewhere (somewhere = a repo in the GitHub organization) to "register" it.

Thoughts?

**Comment by xuanxu** [comment]
As a counter-spam measure GitHub does not allow to programatically manage and accept repository transfers, so this workflow can not be implemented using the API :(

**Comment by maelle** [comment]
Thanks @xuanxu for looking into it!
