### ISSUE TITLE
issue with team creation

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#53]
https://github.com/ropensci/software-review/issues/486#issuecomment-1011139556

@xuanxu this user was already in the GitHub organization. Could this have messed up the team invitation?

**Comment by maelle** [comment]
The team had been created, and had admin access to the repo.

**Comment by maelle** [comment]
I have checked the issue, the author1 is in there.

**Comment by xuanxu** [comment]
I think I found the cause: Currently the responder only invites the author to the team if it creates the team. If the team already exists no invitation is issued. Is it posible that the `gittargets` was already created before finalizing tranfer?

Anyway, I guess we should change that behavior and make the responder invite the author in every case, right?

**Comment by maelle** [comment]
Ah, maybe. @adamhsparks @wlandau, had one of you created the team?

And @xuanxu yes, it sounds like a good idea! Thanks for the debugging!

**Comment by xuanxu** [comment]
👍  [Change](https://github.com/ropensci-org/buffy/commit/99a154da36add50621046a6987a4e6691f241cb6) pushed!

**Comment by maelle** [comment]
Thank you!

**Comment by adamhsparks** [comment]
Sorry, I’ve not created any teams.

**Comment by maelle** [comment]
thanks @adamhsparks!

**Comment by maelle** [comment]
@xuanxu we have this case again

- author already in organization
- the finalize transfer command has created the team but not issued an invitation to the team

I fear the previous bug fix was not the right one.

**Comment by maelle** [comment]
https://github.com/ropensci/software-review/issues/475#issuecomment-1247317853
