### ISSUE TITLE
Reminders?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#56]
Would it a) be possible (question for @xuanxu) and b) make sense (question for everyone) to have the bot write review reminders 2 days before the review deadline or so?

**Comment by xuanxu** [comment]
a) It is totally possible 😄

**Comment by emilyriederer** [comment]
I really like this idea! I might vote for a bit more time like ~4 days which feels imminent but gives reviewers more time to *start* if they haven't - not just to finish

**Comment by maelle** [comment]
Ok so enough votes to make this a feature request for @xuanxu :grin: 

- With reminders 4 days before the deadline.
- Could the reminder text be a parameter/template we might more easily change than if it were in the Ruby code?

**Comment by mpadge** [comment]
And could the number of days before deadline also be a yaml config parameter, rather than hard-coded?

**Comment by jooolia** [comment]
I like it! I try to put some of these deadlines on my calendar (for myself as a reviewer or for others in the role of an editor), but I would find it very helpful to know there will be an automated nudge.

**Comment by maelle** [comment]
Now deployed. For reviewers assigned from now there will be a reminder 2 days before the review due date, at the same time as the time at which the reviewer was added.
