### ISSUE TITLE
Automate hold reminders

### ISSUE THREAD

**Issue by maurolepore** [ropensci-org/buffy#64]
As an editor I would like to have a command to ask the bot to remind  a package-author that their package remains on hold, and the time left before the issue is closed, maybe by quoting this piece from the docs:

> The author can choose to have their submission put on hold (editor applies the holding label). The holding status will be revisited every 3 months, and after one year the issue will be closed.

https://devdevguide.netlify.app/policies.html#policiesreviewprocess

Once reached the time-limit, I would like the bot to close the issue, maybe quoting the docs again and inviting the authors to re-submit?

**Comment by maelle** [comment]
Related to #56 (at least I suppose there's some common logic @xuanxu)

**Comment by maelle** [comment]
How about rather once the time limit is reached, the editor is pinged so they can close the issue? Rather than an automated closing.

**Comment by maelle** [comment]
Now deployed. For reviewers assigned from now there will be a reminder 2 days before the review due date, at the same time as the time at which the reviewer was added.

**Comment by maelle** [comment]
I closed the wrong issue!

**Comment by maelle** [comment]
@maurolepore the command is `@ropensci-review-bot put on hold`
