### ISSUE TITLE
Make it possible to submit a review without time

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#69]
@xuanxu at the moment writing

```
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/505#issuecomment-1090531882 time NA
```

doesn't work as NA isn't a number. Would it be possible for this to work so reviews can be logged in even before reviewers state the time spent (after an editor reminds them)?

**Comment by xuanxu** [comment]
@maelle: Ready here: #70

**Comment by maelle** [comment]
Thank you!!

**Comment by maelle** [comment]
yay https://github.com/ropensci/software-review/issues/505#issuecomment-1091665937
