### ISSUE TITLE
Custom responder for approval that creates a team and invites the submitter to the organization & team

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#8]
@xuanxu 

Currently the "approve" command only uses a template.

Ideally it would, before posting the template answer

* create a team in the ropensci organization named like the package repository (so I suppose we'd need HTML comments in the issue body?)
* invite the person who opened the issue to the ropensci organization and team as member.

Now in the future it'd be great to also invite other authors of the package but for that we'd need a more complicated structure of HTML comments in the issue body, so I think we can't do that until we use some sort of form-based submission.

**Comment by xuanxu** [comment]
About the name of the team, there are a couple of options:
* we could get it from a value marked with HTML comments in the issue body. Need changes in the template.
* it could be passed to the command: `@helper-bot approve repo-package-name`. Requires all editors to remember how the command works and pass the team name.

I think the first option is easier for the editors, but the second one gives them the flexibility to set the name to whatever.

**Comment by maelle** [comment]
Thanks! Maybe the second option is the best indeed, I am now also thinking the package name can have changed during review.
