### ISSUE TITLE
New external service to check stats documentation

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#80]
@xuanxu @maelle I'm pretty sure you can both ignore this one. Implementation should just work.

@noamross Idea here is to implement a command for pre-submission stats enquiries, `@ropensci-review-bot check srr`, which will report on standards compliance to report total number of standards complied with, and confirm that that is > 50%. Any thoughts or comments?

**Comment by xuanxu** [comment]
> * We don't want buffy to send any message here. Is that done with `message:` -> empty body?

No need for an empty body, if there is no `message:` param nothing will be sent

> * We also don't want buffy to deliver any response from the external service; how do we ensure that? The service itself will dump the response (which may take some minutes).

For this you can use the silent param: `silent: true` will do

**Comment by mpadge** [comment]
Thanks @xuanxu, i think i've got everything in place now, including the external service spec via the above PR, but the command [was not recognised](https://github.com/ropensci/software-review/issues/549#issuecomment-1185531717). Any ideas why not?

**Comment by xuanxu** [comment]
Is the command listed if you run `@ropensci-review-bot help` ?

**Comment by mpadge** [comment]
Nope

**Comment by xuanxu** [comment]
I saw the problem: the external_service is repetead in the config file, defined multiple times. All external services should be declared as an array under the same `external_service` entry

**Comment by mpadge** [comment]
@xuanxu (I've been away on holidays, but now back and still trying to get this to work ..) The new config file with the external service matrix is this:
https://github.com/ropensci-org/buffy/blob/dbbc066cdaaaf401f7cd4255328b8078dafad10c/config/settings-production.yml#L107-L140

The requests as sent to the external service then look like this:

```
GET /editorcheck ?data_from_issue%5B%5D=repo&data_from_issue%5B%5D=repourl&data_from_issue%5B%5D=issue_id&secret 200 0.002
GET /srrcheck ?data_from_issue%5B%5D=repo&data_from_issue%5B%5D=repourl&data_from_issue%5B%5D=issue_id&secret 200 0.002
```

so it seems buffy is sending an empty `data_from_issue` parameter instead of actually parsing the array for the variables and values. Does that seem right to you?

**Comment by xuanxu** [comment]
:wave: @mpadge I've open a PR to fix the problem: https://github.com/ropensci-org/buffy/pull/83

**Comment by maelle** [comment]
Can this be closed or are there remaining problems?
