### ISSUE TITLE
stats_badge server error?

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#86]
@xuanxu We had a [recent approval](https://github.com/ropensci/software-review/issues/475) which appears to have generated a new "approved" label (`6pproved-silver-v0.1.0.013`). I guess this server in the `stats_grade_worker` is external to the buffy repo? 

https://github.com/ropensci-org/buffy/blob/746dd74a1dd18feafe9948c0717d91dccb73cfe1/app/workers/ropensci/stats_grade_worker.rb#L18

The grade is supposed to be taken from the version, but regex'ed down to the first 2 components only, so "v0.1" and not "v0.1.0.013". Plus there's another :bug: there with `6pproved` instead of `6/approved`. Can you help debug please? Thanks :+1:

**Comment by xuanxu** [comment]
Yeah, that worker is generating an external call to this URL:
http://138.68.123.59:8000/stats_badge?repo=ropensci/software-review&issue_num=475

The JOSN response I'm getting now is: 
```json
["6\u0007pproved-silver-v0.1.0.013"] 
```
so that is the label applied to the issue. 

Without access to the code in that server is difficult to know why both the `u0007` instead of `A` and the `v0.1.0.013` instead of the proper `0.0.1` are happening

**Comment by mpadge** [comment]
Oh yeah, thanks, that's definitely at our end - sorry, i forgot that i had deployed that server myself. Shall fix that internally now, and close this.

**Comment by mpadge** [comment]
sorry, re-opening because one :bug: is then on this site. The value delivered starts with "6\approved-", but when converted to issue label becomes "6pproved-", so the "\a" is interpreted as an escaped character and not rendered as is. Can you fix that on this side, or shall i instead issue "6\\\\approved" - double escaped?

**Comment by xuanxu** [comment]
Maybe the stats server is using the wrong slash? The rest of the labels use `/` instead of `\`.

**Comment by mpadge** [comment]
oh yeah, right. that was a bit silly of me :confused:
